create table if not exists users (
  id integer generated by default as identity primary key,
  email varchar not null unique,
  hashed_password varchar not null,
  name varchar not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_users_id on users (id);
create index if not exists ix_users_email on users (email);

create table if not exists facebook_connections (
  id integer generated by default as identity primary key,
  user_id integer not null unique references users(id) on delete cascade,
  page_id varchar not null,
  page_name varchar not null,
  page_access_token text not null,
  instagram_business_account_id varchar,
  long_lived_user_token text not null,
  token_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists ix_facebook_connections_id on facebook_connections (id);
create index if not exists ix_facebook_connections_user_id on facebook_connections (user_id);

create table if not exists schedules (
  id integer generated by default as identity primary key,
  user_id integer not null unique references users(id) on delete cascade,
  niche text not null,
  post_time varchar not null,
  timezone varchar not null default 'UTC',
  active boolean not null default true
);

create index if not exists ix_schedules_id on schedules (id);
create index if not exists ix_schedules_user_id on schedules (user_id);

create table if not exists post_logs (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  facebook_connection_id integer not null references facebook_connections(id) on delete cascade,
  content text not null,
  status varchar not null default 'draft',
  error_message text,
  posted_at timestamptz,
  post_date date
);

create index if not exists ix_post_logs_id on post_logs (id);
create index if not exists ix_post_logs_user_id on post_logs (user_id);
create index if not exists ix_post_logs_facebook_connection_id on post_logs (facebook_connection_id);
create index if not exists ix_post_logs_status on post_logs (status);
create index if not exists ix_post_logs_post_date on post_logs (post_date);