services:
  - type: web
    name: auto-poster-backend
    runtime: image
    repo: https://github.com/Mohammad35786/AUTOPOST.git
    plan: free
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_REDIRECT_URI
        value: https://autopost-1-ax2p.onrender.com/auth/facebook/callback
      - key: FACEBOOK_TOKEN_ENCRYPTION_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://autopost-woad.vercel.app
      - key: BACKEND_URL
        value: https://autopost-1-ax2p.onrender.com
      - key: CRON_SECRET
        sync: false
      - key: QSTASH_TOKEN
        sync: false
      - key: QSTASH_CURRENT_SIGNING_KEY
        sync: false
      - key: QSTASH_NEXT_SIGNING_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
