-- Repair schema required by persona edit/save and post scheduling.
-- Safe to run multiple times on Postgres/Supabase.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS prompt_config JSONB;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS custom_prompt TEXT;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS creativity_level INTEGER DEFAULT 7 NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS learning_mode_enabled BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS minimum_engagement_threshold NUMERIC(10,4) DEFAULT 0 NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS learned_patterns_summary TEXT;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS include_image BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS image_frequency VARCHAR DEFAULT 'every_post' NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS image_prompt_source VARCHAR DEFAULT 'persona_prompt' NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS image_fallback_policy VARCHAR DEFAULT 'text_only' NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS image_max_wait_seconds INTEGER DEFAULT 120 NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS template_image_generation_enabled BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE ai_personas ADD COLUMN IF NOT EXISTS template_logo_url TEXT;
CREATE TABLE IF NOT EXISTS persona_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    persona_id INTEGER NOT NULL UNIQUE REFERENCES ai_personas(id) ON DELETE CASCADE,
    timezone VARCHAR NOT NULL DEFAULT 'Asia/Dhaka',
    active_days JSONB NOT NULL DEFAULT '[]'::jsonb,
    default_times JSONB NOT NULL DEFAULT '[]'::jsonb,
    day_overrides JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE persona_schedules ADD COLUMN IF NOT EXISTS timezone VARCHAR DEFAULT 'Asia/Dhaka' NOT NULL;
ALTER TABLE persona_schedules ADD COLUMN IF NOT EXISTS active_days JSONB DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE persona_schedules ADD COLUMN IF NOT EXISTS default_times JSONB DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE persona_schedules ADD COLUMN IF NOT EXISTS day_overrides JSONB DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE persona_schedules ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE persona_schedules ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
ALTER TABLE persona_schedules ALTER COLUMN active_days TYPE JSONB USING active_days::jsonb;
ALTER TABLE persona_schedules ALTER COLUMN default_times TYPE JSONB USING default_times::jsonb;
ALTER TABLE persona_schedules ALTER COLUMN day_overrides TYPE JSONB USING day_overrides::jsonb;

-- Migrate legacy schedule columns only if they exist. Some databases have
-- already dropped days_of_week/post_times, so an unconditional UPDATE fails.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'persona_schedules' AND column_name = 'days_of_week'
    ) THEN
        UPDATE persona_schedules
        SET active_days = to_jsonb(days_of_week)
        WHERE (active_days IS NULL OR active_days = '[]'::jsonb)
          AND days_of_week IS NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'persona_schedules' AND column_name = 'post_times'
    ) THEN
        UPDATE persona_schedules
        SET default_times = to_jsonb(post_times)
        WHERE (default_times IS NULL OR default_times = '[]'::jsonb)
          AND post_times IS NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'persona_schedules' AND column_name = 'schedule_data'
    ) THEN
        UPDATE persona_schedules
        SET
            active_days = COALESCE((schedule_data::jsonb)->'active_days', active_days::jsonb, '[]'::jsonb),
            default_times = COALESCE((schedule_data::jsonb)->'default_times', default_times::jsonb, '[]'::jsonb),
            day_overrides = COALESCE((schedule_data::jsonb)->'day_overrides', day_overrides::jsonb, '{}'::jsonb)
        WHERE schedule_data IS NOT NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS prompt_templates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    persona_id INTEGER NOT NULL REFERENCES ai_personas(id) ON DELETE CASCADE,
    template_name VARCHAR NOT NULL DEFAULT 'Custom',
    question_answers JSONB NOT NULL DEFAULT '{}'::jsonb,
    assembled_prompt TEXT,
    raw_prompt TEXT,
    creativity_level INTEGER NOT NULL DEFAULT 7,
    style_examples JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS template_name VARCHAR DEFAULT 'Custom' NOT NULL;
ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS question_answers JSONB DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS assembled_prompt TEXT;
ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS raw_prompt TEXT;
ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS creativity_level INTEGER DEFAULT 7 NOT NULL;
ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS style_examples JSONB DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE prompt_templates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
CREATE INDEX IF NOT EXISTS idx_prompt_templates_persona_id ON prompt_templates(persona_id);
CREATE INDEX IF NOT EXISTS idx_prompt_templates_user_id ON prompt_templates(user_id);

CREATE TABLE IF NOT EXISTS image_prompt_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    persona_id INTEGER NOT NULL REFERENCES ai_personas(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject_description TEXT,
    style_tags JSONB,
    mood_tags JSONB,
    color_palette VARCHAR,
    negative_prompt TEXT,
    aspect_ratio VARCHAR DEFAULT '1:1' NOT NULL,
    text_overlay_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    text_overlay_content TEXT,
    text_overlay_style VARCHAR,
    reference_image_descriptors TEXT,
    assembled_prompt TEXT,
    reference_image_url TEXT,
    template_layers_json JSONB,
    template_analyzed_at TIMESTAMPTZ,
    template_logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(persona_id)
);

ALTER TABLE image_prompt_settings ADD COLUMN IF NOT EXISTS reference_image_url TEXT;
ALTER TABLE image_prompt_settings ADD COLUMN IF NOT EXISTS template_layers_json JSONB;
ALTER TABLE image_prompt_settings ADD COLUMN IF NOT EXISTS template_analyzed_at TIMESTAMPTZ;
ALTER TABLE image_prompt_settings ADD COLUMN IF NOT EXISTS template_logo_url TEXT;
ALTER TABLE image_prompt_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;

CREATE INDEX IF NOT EXISTS idx_persona_schedules_persona_id ON persona_schedules(persona_id);

CREATE TABLE IF NOT EXISTS scheduled_slots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    persona_id INTEGER NOT NULL REFERENCES ai_personas(id) ON DELETE CASCADE,
    scheduled_at TIMESTAMPTZ NOT NULL,
    qstash_message_id VARCHAR,
    status VARCHAR NOT NULL DEFAULT 'pending',
    post_id INTEGER REFERENCES post_logs(id) ON DELETE SET NULL,
    error_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE scheduled_slots ADD COLUMN IF NOT EXISTS qstash_message_id VARCHAR;
ALTER TABLE scheduled_slots ADD COLUMN IF NOT EXISTS post_id INTEGER;
ALTER TABLE scheduled_slots ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE scheduled_slots ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE scheduled_slots ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
CREATE INDEX IF NOT EXISTS idx_scheduled_slots_persona_id ON scheduled_slots(persona_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_slots_scheduled_at ON scheduled_slots(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_scheduled_slots_status ON scheduled_slots(status);
CREATE INDEX IF NOT EXISTS ix_scheduled_slots_status_time ON scheduled_slots(status, scheduled_at);

ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS qstash_message_id VARCHAR;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS delivery_status VARCHAR DEFAULT 'pending' NOT NULL;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS media_urls JSONB DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS link_url TEXT;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS link_preview_data JSONB;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE post_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL;
